config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  root "quotes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.order(:created_at => :desc).paginate(page: params[:page], per_page: 12)
    # @quotes = Quote.paginate(page: params[:page], per_page: 12)
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    if @quote.author.strip != "" && @quote.content.strip != ""
      redirect_to quotes_path, notice: 'Quote was successfully created.' if @quote.save 
    else
      flash.now.alert = "You need to type something here!"
      # redirect_to new_quote_path, alert: "You need to type something here!"
      render :new
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top Quality Quotes!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="alert-wrapper">
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    <div class="notice-wrapper">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
    </div>
    <%= yield %>
    <footer>
      Icons made by <a href="http://www.freepik.com" title="Freepik" target="_blank" rel="noopener">Freepik</a> and <a href="https://www.flaticon.com/authors/spovv" title="spovv" target="_blank" rel="noopener">spovv</a> from <a href="https://www.flaticon.com/" target="_blank" rel="noopener">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licences/by/3.0/" title="Creative Commons BY 3.0" target="_blank" rel="noopener">CC 3.0 BY</a>
    </footer>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit data: { disable_with: false } %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<div class="wrapper">
	<div>
		<h1>Editing Quote</h1>

		<%= render 'form', quote: @quote %>

		<%= link_to 'Back', quotes_path %>
	</div>
</div>

app/views/quotes/index.html.erb
<div class="wrapper">
  <h1>Top quality quotes!</h1>
  <% @quotes.each do |quote| %>
    <div class="citation-container">
      <div class="quote-div">
        <q><%= quote.content %></q>
        <cite><%= quote.author %></cite>
      </div>
      <div class="operations-div">
        <div class="operations-on-quotes">
          <%= link_to image_tag("pencil-edit-button.png"), edit_quote_path(quote) %>
          <%= link_to image_tag("trash-can.png"), quote, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <time><%= quote.created_at.strftime("%d %B %Y") %></time>
      </div>
    </div>
  <% end %>
  <div class="new">
      <%= link_to 'New quote', new_quote_path %>
    </div>
  <%= will_paginate @quotes, previous_label: h("< "), next_label: h("> ") %>
  </div>

app/views/quotes/new.html.erb
<div class="wrapper">
	<div>
		<h1>New Quote</h1>

		<%= render 'form', quote: @quote %>

		<%= link_to 'Back', quotes_path %>
	</div>
</div>

app/views/quotes/show.html.erb
<div class="wrapper">
	<div class="citation-container">
		<div class="quote-div">
			<q>
			  <%= @quote.content %>
			</q>
			<cite>
			  <%= @quote.author %>
			</cite>
		</div>
		<div class="operations-div">
			<div class="operations-on-quotes">
			    <%= link_to image_tag("pencil-edit-button.png"), edit_quote_path(@quote) %>
			    <%= link_to image_tag("trash-can.png"), @quote, method: :delete, data: { confirm: 'Are you sure?' } %> 
		     </div>
		      <%= link_to 'Back', quotes_path %>
	    </div>
	</div>
</div>